"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# from setuptools import setup
#
# APP = ['iCake.py']
# DATA_FILES = ['file']
# OPTIONS = {'argv_emulation': True}
#
# setup(
#     app=APP,
#     data_files=DATA_FILES,
#     options={'py2app': OPTIONS},
#     setup_requires=['py2app'],
# )

application_title = "iCake" #what you want to application to be called
main_python_file = "iCake.py" #the name of the python file you use to run the program

import sys

from cx_Freeze import setup, Executable

base = None
if sys.platform == "win32":
    base = "Win32GUI"

includes = ["atexit","re"]
includefiles = ['file']

setup(
        name = application_title,
        version = "0.1",
        description = "Sample cx_Freeze PyQt4 script",
        options = {"build_exe" : {"includes" : includes,'include_files':includefiles}},
        executables = [Executable(main_python_file, base = base)])
